#!/usr/bin/python

import sys
import traceback

from PyQt4 import QtGui

import Windows

def wrowserExceptHook(eType, eValue, eTraceback):
    message = "".join(traceback.format_exception(eType, eValue, eTraceback))
    print message
    response = QtGui.QMessageBox.critical(QtGui.QApplication.activeWindow(), "Python Exception", message, "Exit", "Debug", "Continue")
    if response == 0:
        sys.exit(255)
    elif response == 1:
        import pdb
        pdb.set_trace()
    else:
        pass

if __name__ == "__main__":
    application = QtGui.QApplication(sys.argv)
    application.setQuitOnLastWindowClosed(True)
    application.setApplicationName("Wrowser")
    application.setWindowIcon(QtGui.QIcon("icon.png"))
    application.setOrganizationName("RWTH Aachen University - ComNets")
    application.setOrganizationDomain("www.comnets.rwth-aachen.de")
    widget = Windows.Main()
    widget.show()
    sys.excepthook = wrowserExceptHook
    sys.exit(application.exec_())
